//@version=4
study(title="MFI + RSI Buy-Sell Signals", shorttitle="MFI/RSI CONV/DIV", format=format.price, precision=2, resolution="")

//MFI Inputs
slope_period = input(1, title="SLOPE PERIOD", minval=1)
lengthMFI1 = input(title="Length MFI 1", type=input.integer, defval=8, minval=1, maxval=2000)
lengthMFI2 = input(title="Length MFI 2", type=input.integer, defval=13, minval=1, maxval=2000)
lengthMFI3 = input(title="Length MFI 3", type=input.integer, defval=21, minval=1, maxval=2000)

src = hlc3

lengthMFIHMA1 = input(3, title="AVERAGE LENGTH HMA1", minval=1)
lengthMFIHMA2 = input(5, title="AVERAGE LENGTH HMA2", minval=1)
lengthMFIHMA3 = input(8, title="AVERAGE LENGTH HMA3", minval=1)
lengthMFIHMA4 = input(13, title="AVERAGE LENGTH HMA4", minval=1)
lengthMFIHMA5 = input(34, title="AVERAGE LENGTH HMA5", minval=1)

lengthMFIEMA1 = input(13, title="AVERAGE LENGTH EMA1", minval=1)
lengthMFIEMA2 = input(55, title="AVERAGE LENGTH EMA1", minval=1)

//RSI INPUTS
RSIlength = input(14, title="RSI LENGTH", minval=1)
lengthRSIHMA1 = input(3, title="AVERAGE LENGTH HMA1", minval=1)
lengthRSIHMA2 = input(5, title="AVERAGE LENGTH HMA2", minval=1)
lengthRSIHMA3 = input(8, title="AVERAGE LENGTH HMA3", minval=1)
lengthRSIHMA4 = input(13, title="AVERAGE LENGTH HMA4", minval=1)
lengthRSIHMA5 = input(34, title="AVERAGE LENGTH HMA5", minval=1)

lengthRSIEMA1 = input(8, title="AVERAGE LENGTH EMA1", minval=1)
lengthRSIEMA2 = input(21, title="AVERAGE LENGTH EMA2", minval=1)

lenRSI1 = input(6, minval=1, title="RSI 1 Length")
lenRSI2 = input(13, minval=1, title="RSI 2 Length")
lenRSI3 = input(21, minval=1, title="RSI 3 Length")
srcRSI = input(close, "Source RSI", type = input.source)

//RSI CALCULATIONS
up1 = rma(max(change(srcRSI), 0), lenRSI1)
down1 = rma(-min(change(srcRSI), 0), lenRSI1)
up2 = rma(max(change(srcRSI), 0), lenRSI2)
down2 = rma(-min(change(srcRSI), 0), lenRSI2)
up3 = rma(max(change(srcRSI), 0), lenRSI3)
down3 = rma(-min(change(srcRSI), 0), lenRSI3)

rsi1 = down1 == 0 ? 100 : up1 == 0 ? 0 : 100 - (100 / (1 + up1 / down1))
rsi2 = down2 == 0 ? 100 : up2 == 0 ? 0 : 100 - (100 / (1 + up2 / down2))
rsi3 = down3 == 0 ? 100 : up3 == 0 ? 0 : 100 - (100 / (1 + up3 / down3))
avgrsi = (rsi1 + rsi2 + rsi3) / 3

//HMA of RSI
hmaRSI1 = wma(2*wma(avgrsi, lengthRSIHMA1/2)-wma(avgrsi, lengthRSIHMA1), round(sqrt(lengthRSIHMA1)))

hmaRSI2 = wma(2*wma(avgrsi, lengthRSIHMA2/2)-wma(avgrsi, lengthRSIHMA2), round(sqrt(lengthRSIHMA2)))

hmaRSI3 = wma(2*wma(avgrsi, lengthRSIHMA3/2)-wma(avgrsi, lengthRSIHMA3), round(sqrt(lengthRSIHMA3)))

hmaRSI4 = wma(2*wma(avgrsi, lengthRSIHMA4/2)-wma(avgrsi, lengthRSIHMA4), round(sqrt(lengthRSIHMA4)))

hmaRSI5 = wma(2*wma(avgrsi, lengthRSIHMA5/2)-wma(avgrsi, lengthRSIHMA5), round(sqrt(lengthRSIHMA5)))

//EMA1 of avgrsi
emaRSI1 = ema(avgrsi, lengthRSIEMA1)

//Slope of EMA1
emaRSI1Slope = (emaRSI1 - emaRSI1[slope_period]) / slope_period

//EMA2 of avgrsi
emaRSI2 = ema(avgrsi, lengthRSIEMA2)

//Slope of EMA2
emaRSI2Slope = (emaRSI2 - emaRSI2[slope_period]) / slope_period

//AVERAGE MOVING AVERAGE (AMA) of RSI
amaRSI = (hmaRSI1 + hmaRSI2 + hmaRSI3 + hmaRSI4 + hmaRSI5) / 5

//Slope of AMA
amaRSISlope = (amaRSI - amaRSI[slope_period]) / slope_period

//MFI CALCULATIONS
upper1 = sum(volume * (change(src) <= 0 ? 0 : src), lengthMFI1)
lower1 = sum(volume * (change(src) >= 0 ? 0 : src), lengthMFI1)
upper2 = sum(volume * (change(src) <= 0 ? 0 : src), lengthMFI2)
lower2 = sum(volume * (change(src) >= 0 ? 0 : src), lengthMFI2)
upper3 = sum(volume * (change(src) <= 0 ? 0 : src), lengthMFI3)
lower3 = sum(volume * (change(src) >= 0 ? 0 : src), lengthMFI3)
_rsi(upper, lower) =>
    if lower == 0
        100
    if upper == 0
        0
	100.0 - (100.0 / (1.0 + upper / lower))
mf1 = _rsi(upper1, lower1)
mf2 = _rsi(upper2, lower2)
mf3 = _rsi(upper3, lower3)
mfAvg = (mf1 + mf2 + mf3) / 3


//Moving Average
hmaMFI1 = wma(2*wma(mfAvg, lengthMFIHMA1/2)-wma(mfAvg, lengthMFIHMA1), round(sqrt(lengthMFIHMA1)))

hmaMFI2 = wma(2*wma(mfAvg, lengthMFIHMA2/2)-wma(mfAvg, lengthMFIHMA2), round(sqrt(lengthMFIHMA2)))

hmaMFI3 = wma(2*wma(mfAvg, lengthMFIHMA3/2)-wma(mfAvg, lengthMFIHMA3), round(sqrt(lengthMFIHMA3)))

hmaMFI4 = wma(2*wma(mfAvg, lengthMFIHMA4/2)-wma(mfAvg, lengthMFIHMA4), round(sqrt(lengthMFIHMA4)))

hmaMFI5 = wma(2*wma(mfAvg, lengthMFIHMA5/2)-wma(mfAvg, lengthMFIHMA5), round(sqrt(lengthMFIHMA5)))

//EMA1 of MFG
emaMFI1 = ema(mfAvg, lengthMFIEMA1)

//Slope of EMA1
emaMFI1Slope = (emaMFI1 - emaMFI1[slope_period]) / slope_period

//EMA2 of MFG
emaMFI2 = ema(mfAvg, lengthMFIEMA2)

//Slope of EMA2
emaMFI2Slope = (emaMFI2 - emaMFI2[slope_period]) / slope_period

//AMA of MFI
amaMFI = (hmaMFI1 + hmaMFI2 + hmaMFI3 + hmaMFI4 + hmaMFI5) / 5

//Slope of AMA
amaMFISlope = (amaMFI - amaMFI[slope_period]) / slope_period

//Plot MFI

//plot(mfAvg, "MF AVG", color=color.green, transp=50)
//plot(mf1, "MF1", color=color.green)
//plot(mf2, "MF2", color=color.orange)
//plot(mf3, "MF3", color=color.white)
//plot(amaMFI, "AMA", color=amaSlope > 0 ? color.yellow : color.red)
//plot(emaMFI1, "EMA1", color=ema1Slope > 0 ? color.yellow : color.red, transp=50)
//plot(emaMFI2, "EMA2", color=ema2Slope > 0 ? color.yellow : color.red, transp=50)
//overbought=hline(80, title="Overbought", color=#c0c0c0)
//oversold=hline(20, title="Oversold", color=#c0c0c0)
//midline=hline(50, title="Midline", color=#c0c0c0)
//fill(overbought, oversold, color=#9915ff, transp=90, title="Background")

//PLOT RSI

bgcolor(amaRSISlope < 0 and emaRSI1Slope < 0 and amaRSI < emaRSI1 and amaRSI < emaRSI2 and emaRSI2Slope < 0 and emaMFI1Slope < 0 and emaMFI2Slope < 0  ? color.red : color.green, editable=false, title="Direction Changes", transp=80)
