//@version=4
study("RSI Slope HMA", overlay=false)

//inputs
RSIlength = input(14, title="RSI LENGTH", minval=1)
lengthHMA1 = input(3, title="AVERAGE LENGTH HMA1", minval=1)
lengthHMA2 = input(5, title="AVERAGE LENGTH HMA2", minval=1)
lengthHMA3 = input(8, title="AVERAGE LENGTH HMA3", minval=1)
lengthHMA4 = input(13, title="AVERAGE LENGTH HMA4", minval=1)
lengthHMA5 = input(34, title="AVERAGE LENGTH HMA5", minval=1)
lengthEMA = input(14, title="AVERAGE LENGTH EMA", minval=1)
lengthSMA = input(14, title="AVERAGE LENGTH SMA", minval=1)

slope_period = input(1, title="SLOPE PERIOD", minval=1)

len1 = input(6, minval=1, title="RSI 1 Length")
len2 = input(13, minval=1, title="RSI 2 Length")
len3 = input(21, minval=1, title="RSI 3 Length")
src = input(close, "Source", type = input.source)

//CALCULATE RSI//
up1 = rma(max(change(src), 0), len1)
down1 = rma(-min(change(src), 0), len1)
up2 = rma(max(change(src), 0), len2)
down2 = rma(-min(change(src), 0), len2)
up3 = rma(max(change(src), 0), len3)
down3 = rma(-min(change(src), 0), len3)

rsi1 = down1 == 0 ? 100 : up1 == 0 ? 0 : 100 - (100 / (1 + up1 / down1))
rsi2 = down2 == 0 ? 100 : up2 == 0 ? 0 : 100 - (100 / (1 + up2 / down2))
rsi3 = down3 == 0 ? 100 : up3 == 0 ? 0 : 100 - (100 / (1 + up3 / down3))
avgrsi = (rsi1 + rsi2 + rsi3) / 3

//HMA of RSI
hma1 = wma(2*wma(avgrsi, lengthHMA1/2)-wma(avgrsi, lengthHMA1), round(sqrt(lengthHMA1)))

hma2 = wma(2*wma(avgrsi, lengthHMA2/2)-wma(avgrsi, lengthHMA2), round(sqrt(lengthHMA2)))

hma3 = wma(2*wma(avgrsi, lengthHMA3/2)-wma(avgrsi, lengthHMA3), round(sqrt(lengthHMA3)))

hma4 = wma(2*wma(avgrsi, lengthHMA4/2)-wma(avgrsi, lengthHMA4), round(sqrt(lengthHMA4)))

hma5 = wma(2*wma(avgrsi, lengthHMA5/2)-wma(avgrsi, lengthHMA5), round(sqrt(lengthHMA5)))

//EMA of avgrsi
ema = ema(avgrsi, lengthEMA)

//SMA of avgrsi
sma = sma(avgrsi, lengthSMA)

//AVERAGE MOVING AVERAGE (AMA) of RSI
ama = (hma1 + hma2 + hma3 + hma4 + hma5 + sma + ema) / 7

//Slope of AMA
amaSlope = (ama - ama[slope_period]) / slope_period

plotColour2 = amaSlope > 0 ? color.yellow : color.red


plot(avgrsi, color=color.blue, title="AMA RSI", linewidth=1, transp=50)
//plot(RSIslope, color = plotColour, linewidth=2, transp=0)
//plot(ema, color=plotColour2, title="ema", linewidth=1, transp=50)
//plot(sma, color=plotColour2, title="sma", linewidth=1, transp=50)
//plot(hma1, color=plotColour2, title="hma", linewidth=1, transp=50)
plot(ama, color=plotColour2, title="ama", linewidth=3, transp=10)


//HORIZONTAL LINES
band2 = hline(50, "Upper Band", color=#C0C0C0, linewidth=3)
band1 = hline(70, "Upper Band", color=#C0C0C0)
band0 = hline(30, "Lower Band", color=#C0C0C0)

//BACKGROUND COLOR
bgcolor(plotColour2 == color.yellow ? color.green : color.red, editable=false, title="Direction Changes")

//Add: Alerts
alertcondition(plotColour2 == color.orange, title='BEARISH RSI MA SLOPE', message='BEARISH RSI SLOPE')
alertcondition(plotColour2 == color.yellow, title='BULLISH RSI MA SLOPE', message='BULLISH RSI MA SLOPE')

